SET NAMES utf8mb4;

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-01', 3, 'تعثر مورد أساسي قبل موعد الإطلاق', 'تدير مشروعاً يقترب من مرحلة الإطلاق، وأبلغك المورد الرئيس بأن التسليم سيتأخر. المعلومات المتاحة عن مدة التأخير غير مكتملة، وأي توقف كامل سيؤثر في موعد الإطلاق، بينما استخدام بديل غير مدروس قد يرفع التكلفة أو يهدد الجودة.', 'TRADE_OFF', 'FULL', 'يجمع الخيار (C) بين جمع الحد الأدنى الحرج من المعلومات، وإدارة المخاطر، واستمرارية العمل، والشفافية، ونقطة مراجعة تسمح بتعديل القرار.', 'الانتظار حتى اكتمال جميع البيانات، أو اتخاذ قرار سريع بناءً على التكلفة وحدها.', 'في القرارات العاجلة لا تبحث عن يقين كامل؛ حدد المعلومات التي لا يمكن اتخاذ القرار من دونها، ثم اجعل القرار قابلاً للمراجعة.', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'تفعيل المورد الاحتياطي المعتمد فوراً، ثم إبلاغ الإدارة بعد بدء التنفيذ.', 4, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'تعليق جميع الأعمال إلى أن يرسل المورد الرئيس معلومات كاملة ونهائية.', 2, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'تحديد المعلومات الحرجة سريعاً، ومقارنة البدائل وفق المخاطر والجودة والزمن، وتفعيل حل مؤقت معتمد قابل للمراجعة، ثم إبلاغ الأطراف المعنية بنقاط القرار والمتابعة.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'اختيار البديل الأقل تكلفة حتى لا تتأثر ميزانية المشروع.', 1, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-02', 2, 'تعليمات فُهمت بطرق مختلفة', 'أرسلت تعليمات لتنفيذ إجراء جديد، ثم لاحظت أن أعضاء الفريق فسروها بطرق مختلفة، وبدأ هذا الاختلاف يؤخر التنفيذ.', 'DIRECT', 'FULL', 'الخيار (B) يكشف موضع الالتباس، ويعدل الرسالة، ويستخدم التحقق من الفهم، ثم يوثق ما تم الاتفاق عليه.', 'اعتبار أن تكرار الرسالة بالطريقة نفسها سيحل المشكلة، أو تحميل الفريق المسؤولية قبل فحص وضوح التوجيه.', 'التواصل الفعال لا يكتمل بالإرسال؛ بل بالتأكد من أن المعنى المستلم يطابق المعنى المقصود.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'إرسال رسالة أطول تكرر التعليمات نفسها بمزيد من التفاصيل.', 2, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'عقد تواصل قصير، وطلب شرح الفهم الحالي من الفريق، ثم إعادة صياغة الرسالة وتحديد المسؤوليات والمواعيد، وتثبيت الخلاصة كتابياً.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'إرسال تنبيه بأن أي خطأ لاحق سيعُد تقصيراً في الالتزام بالتوجيهات.', 1, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'تكليف أكثر أعضاء الفريق خبرة بشرح التعليمات للآخرين ومتابعة التطبيق.', 4, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-03', 2, 'عضو مرتفع الأداء يهيمن على العمل', 'يمتلك أحد أعضاء فريقك خبرة مرتفعة، لكنه بدأ يستحوذ على معظم المهام والقرارات، وأصبح بقية الأعضاء أقل مشاركة وأقل إحساساً بالمسؤولية.', 'TRADE_OFF', 'FULL', 'الخيار (C) يحافظ على قيمة العضو، ويعالج الأثر السلوكي مباشرة، ويحول خبرته من احتكار للعمل إلى تمكين للفريق.', 'مكافأة الأداء الفردي مع تجاهل أثره في المسؤولية الجماعية، أو معالجة الموقف بإحراج علني.', 'الفريق القوي لا يعتمد على بطل واحد؛ بل يحول خبرة الأفراد إلى قدرة مشتركة.', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'ترك الوضع كما هو لأن العضو يضمن سرعة الإنجاز وجودته.', 2, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'توجيه ملاحظة علنية له في الاجتماع القادم حتى يدرك أثر سلوكه.', 1, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'مناقشته على انفراد، وتوضيح أثر الهيمنة في نمو الفريق، ثم إعادة توزيع الأدوار وتمكينه من نقل الخبرة ومتابعة مشاركة الجميع.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'إعادة توضيح ملكية المهام ومسارات التسليم للفريق كله، ثم متابعة العضو بصورة فردية لضمان الالتزام.', 4, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-04', 4, 'خلاف بين إدارتين حول المسؤولية', 'تعمل إدارتان على مشروع مشترك، وظهر خلاف حاد حول الجهة المسؤولة عن مرحلة رئيسة. بدأ كل طرف يحمّل الآخر مسؤولية التأخير، وأصبح موعد التسليم مهدداً.', 'TRADE_OFF', 'FULL', 'الخيار (D) يعيد التركيز إلى الهدف، ويستند إلى أدلة، ويحدد الأدوار فوراً من دون تعطيل، ويترك مساراً للمراجعة الرسمية.', 'اختيار طرف بناءً على السلطة، أو تأجيل العمل حتى اكتمال حل تنظيمي طويل.', 'في نزاعات المسؤوليات، حوّل النقاش من الأشخاص إلى المهمة والحدود ونقاط التسليم.', 'D', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'إسناد المهمة إلى الإدارة الأعلى مكانة تنظيمية لإنهاء الجدل سريعاً.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'مطالبة مديري الإدارتين بحل الخلاف بأنفسهما ورفع النتيجة إليك.', 3, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'إيقاف المرحلة المتنازع عليها إلى أن ترُاجع الهياكل والصلاحيات رسمياً.', 2, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'عقد جلسة قصيرة تستند إلى الهدف المشترك والوثائق، وتحديد المسؤوليات ونقاط التسليم بوضوح، واعتماد مسؤولية مؤقتة قابلة للمراجعة مع مسار تصعيد محدد.', 5, 1, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-05', 3, 'تقديم موعد نهائي مع إرهاق الفريق', 'تقرر تقديم موعد تسليم مشروع يومين، بينما أظهر الفريق علامات إرهاق بعد فترة عمل مكثف. المطلوب المحافظة على جودة المخرجات وعدم استنزاف الفريق.', 'TRADE_OFF', 'FULL', 'الخيار (C) يوازن بين النطاق والموارد والوقت، ويحافظ على الاستدامة والشفافية وجودة القرار.', 'ربط القيادة تحت الضغط بزيادة الساعات فقط، أو محاولة إنقاذ الموقف فردياً.', 'عند ضغط الوقت، أعد تصميم العمل قبل أن تطلب جهداً إضافياً.', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'فرض ساعات عمل إضافية على الجميع حتى يكتمل المشروع في الموعد الجديد.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'طلب تمديد الموعد فوراً من دون تقديم بديل أو خطة تنفيذ.', 3, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'تحديد المخرجات الحرجة، والتفاوض على نطاق واقعي، وإعادة توزيع الحمل، ووضع نقاط متابعة قصيرة وفترات تعافٍ، مع إبلاغ الجهة المعنية بالمفاضلات.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'تحمل معظم المهام بنفسك حتى تخفف الضغط عن بقية الفريق.', 2, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-06', 1, 'المفاضلة بين سرعة الإطلاق وجودة التنفيذ', 'أصبح أمامك خمسة أيام فقط لإطلاق خدمة جديدة. الإطلاق الكامل في الوقت المحدد يحمل مخاطر جودة، بينما التأجيل الكامل سيؤدي إلى فقدان فرصة مهمة.', 'TRADE_OFF', 'FULL', 'الخيار (C) يختبر الخدمة في نطاق يمكن التحكم به، ويحمي العناصر الحرجة، ويتيح التعلم والتراجع قبل التوسع.', 'تصوير القرار على أنه اختيار ثنائي بين الإطلاق الكامل والتأجيل الكامل.', 'ابحث عن خيار ثالث يجزئ المخاطرة ويتيح التعلم المرحلي.', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'إطلاق الخدمة كاملة في الموعد، ومعالجة الأخطاء بعد بدء الاستخدام.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'تأجيل الإطلاق حتى تصبح جميع العناصر مثالية بلا استثناء.', 2, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'تنفيذ إطلاق مرحلي محدود يحمي العناصر الحرجة، مع معايير قبول ومراقبة وخطة تراجع قبل التوسع.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'إطلاق الحد الأدنى المتوافق مع المتطلبات، وتأجيل الخصائص غير الحرجة بموافقة أصحاب المصلحة.', 4, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-07', 2, 'اعتراض علني على قرار أثناء اجتماع', 'أثناء اجتماع مهم، اعترض أحد الموظفين على قرارك أمام الحضور، وقدم ملاحظات بنبرة حادة. بعض ملاحظاته قد تكون صحيحة، لكن استمرار النقاش بالطريقة نفسها قد يربك الاجتماع.', 'TRADE_OFF', 'FULL', 'الخيار (B) يفصل بين النبرة والمضمون، ويحافظ على الاحترام، ويستفيد من المعلومة، ويمنع انحراف الاجتماع.', 'الدفاع عن السلطة بدلاً من إدارة الرسالة، أو تجنب الاعتراض بالكامل.', 'استمع للمضمون، اضبط الإطار، ثم أعد النقاش إلى الهدف.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'مقاطعته والتأكيد أن القرار صادر عنك وأن النقاش يجب أن ينتهي.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'الاستماع إلى النقاط الأساسية، وطلب الأدلة، والاعتراف بما يستحق النظر، وتوضيح ما يمكن حسمه الآن وما يحتاج متابعة منفصلة، ثم إعادة الاجتماع إلى هدفه.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'إيقاف النقاش وإبلاغه بأن الموضوع سينُاقش معه على انفراد بعد الاجتماع.', 3, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'طلب تصويت الحضور على القرار حتى لا يبدو أنك تفرض رأيك.', 2, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-08', 2, 'عضو جديد لا يشارك في الفريق', 'انضم موظف جديد إلى فريق قائم منذ مدة، ولاحظت أنه لا يشارك في النقاشات ولا يُكلفّ بمهام ذات قيمة، بينما يعتمد الفريق على أعضائه القدامى.', 'DIRECT', 'FULL', 'الخيار (C) يزيل الغموض، ويخلق دعماً اجتماعياً، ويمنح فرصة عمل حقيقية مع متابعة مناسبة.', 'اعتبار الاندماج مسؤولية الموظف الجديد وحده، أو تكليفه بمهمة تفوق جاهزيته بلا دعم.', 'الاندماج الفعال يحتاج وضوح دور، وعلاقة دعم، ومساهمة ذات معنى.', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'إبلاغ الموظف بأن عليه أن يكون أكثر مبادرة إذا أراد الاندماج.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'منحه فوراً مهمة مركزية كبيرة حتى يثبت قدرته أمام الفريق.', 3, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'توضيح دوره، وتعيين زميل داعم، وإشراكه في النقاش، ومنحه مسؤولية محددة ذات معنى، ثم متابعة اندماجه وتقدمه.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'تذكير الفريق كله بأهمية الشمول وإتاحة المشاركة من دون تسمية أحد.', 4, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-09', 2, 'اعتراض موظف على تقييم أدائه', 'بعد جلسة تقييم أداء، أخبرك أحد الموظفين بأن التقييم غير عادل وأنك لم تراِعِ بعض إنجازاته. أصبح النقاش متوتراً.', 'DIRECT', 'FULL', 'الخيار (B) يجمع الاستماع والعدالة والاستعداد لتصحيح الخطأ، ثم يحول الخلاف إلى خطة أداء قابلة للمتابعة.', 'الدفاع عن القرار لمجرد أنه صدر من القائد، أو التنازل غير المبرر لإرضاء الموظف.', 'العدالة لا تعني الثبات على القرار؛ بل الثبات على المعايير والاستعداد لمراجعة الأدلة.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'التأكيد أن التقييم نهائي وأن قبول الملاحظات جزء من الاحترافية.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'الاستماع إلى اعتراضه، ومراجعة الأدلة والمعايير، وتصحيح التقييم إذا ظهر خطأ، ثم الاتفاق على توقعات ومؤشرات ومراجعة لاحقة.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'إحالة النقاش بالكامل إلى الموارد البشرية لتجنب التصعيد بينكما.', 2, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'رفع التقييم درجة واحدة للمحافظة على العلاقة وإغلاق الموضوع.', 3, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-10', 3, 'تعطل نظام أثناء تقديم خدمة حساسة', 'تعطل نظام أساسي أثناء تقديم خدمة ذات موعد حساس، وبدأت الطلبات تتراكم. لا يعرف العملاء سبب التأخير، والفريق ينتظر توجيهك.', 'TRADE_OFF', 'FULL', 'الخيار (C) يعالج التشغيل والتواصل والمخاطر في وقت واحد، ويستخدم خطة الاستمرارية بدلاً من الارتجال.', 'التركيز على استعادة النظام فقط وإهمال المتعاملين والبيانات والأولويات.', 'تحت الضغط، قسّم الاستجابة إلى: احتواء، استمرارية، تواصل، ثم تعلم.', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'الاستمرار في العمل بأساليب فردية مختلفة حتى يعود النظام.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'إيقاف الخدمة بالكامل وانتظار الفريق التقني من دون إجراءات أخرى.', 3, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'تفعيل خطة الاستمرارية، وتوزيع الأدوار، وحماية البيانات والأولويات الحرجة، وإبلاغ المتعاملين بتحديث واضح، ثم إجراء مراجعة بعد استقرار الوضع.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'تكليف الفريق بمحاولات الاستعادة بينما تتواصل أنت مع الإدارة العليا للحصول على توجيه.', 4, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-11', 5, 'معلومة جديدة تناقض خطة معتمدة', 'وردت بيانات جديدة تشير إلى أن أحد افتراضات الخطة المعتمدة لم يعد صحيحاً. ما زال مصدر البيانات بحاجة إلى تحقق إضافي، لكن تجاهلها قد يزيد الخسائر، بينما تغيير الخطة فوراً قد يسبب اضطراباً واسعاً.', 'ESCALATION', 'FULL', 'الخيار (B) يحقق التحقق المتناسب مع الوقت، ويحد من نطاق التغيير، ويستمر في الأعمال الآمنة، ويقدم توصية واضحة.', 'التمسك بالخطة حفاظاً على الاتساق، أو تغييرها كاملة بدافع الخوف.', 'فرّق بين ما يجب تجميده، وما يمكن استمراره، وما يحتاج قراراً جديداً.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'الاستمرار بالخطة حتى موعد المراجعة الرسمي لأن التغيير الآن سيضعف الثقة.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'التحقق سريعاً من المصدر والأثر، وبناء سيناريوهات، ورفع توصية مدعومة، وتعديل الأجزاء المتأثرة فقط مع استمرار الأعمال غير المتأثرة.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'تغيير الخطة كاملة فوراً استناداً إلى البيانات الجديدة تحسباً لأسوأ احتمال.', 2, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'إرسال البيانات للإدارة العليا وانتظار قرارها قبل اتخاذ أي خطوة.', 3, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-12', 5, 'إعلان تغيير يؤثر في عدة فرق', 'ستطبق المؤسسة تغييراً في طريقة العمل يؤثر في عدة إدارات بدرجات مختلفة. ظهرت شائعات ومخاوف قبل الإعلان الرسمي.', 'TRADE_OFF', 'FULL', 'الخيار (C) يجمع الاتساق والتخصيص والشفافية والقنوات الراجعة والتحقق من الفهم.', 'الخلط بين توحيد الرسالة وتوحيد تفاصيلها لجميع الفئات، أو إخفاء المعلومات لتجنب القلق.', 'رسالة التغيير الفعالة تجيب عن: لماذا؟ ماذا؟ متى؟ ما الأثر؟ وأين أطرح سؤالي؟', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'إرسال رسالة موحدة قصيرة تذكر موعد التطبيق فقط حتى لا تتعدد التفسيرات.', 2, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'ترك كل مدير يشرح التغيير لفريقه بالطريقة التي يراها مناسبة.', 3, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'إعداد رسالة موحدة تشرح سبب التغيير وما سيتغير وما لن يتغير، وتخصيص أثر كل فئة، وتوفير جدول وقنوات أسئلة، والتحقق من الفهم عبر المديرين.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'تأجيل الإعلان إلى ما بعد بدء التطبيق حتى لا تزداد المقاومة مسبقاً.', 1, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-13', 2, 'تفاوت واضح في عبء العمل', 'لاحظت أن ثلاثة أعضاء يتحملون معظم المهام العاجلة، بينما يملك بقية الفريق وقتاً متاحاً، وبدأ الإرهاق والاستياء يظهران.', 'DIRECT', 'FULL', 'الخيار (B) يعالج الحمل والأولويات والقدرات ويحوّل إعادة التوزيع إلى فرصة تطوير مع متابعة مستدامة.', 'المساواة العددية بدلاً من العدالة، أو الاعتماد الدائم على الأكثر كفاءة.', 'وزّع العمل وفق الأولوية والقدرة، ثم طوّر القدرة حتى لا يظل التوزيع مختلاً.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'مطالبة الأعضاء الأكثر انشغالاً ببذل جهد إضافي لأنهم الأكثر خبرة.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'تحليل الأولويات والقدرات، وإعادة توزيع العمل بشفافية، وتوفير دعم أو تعلم سريع، ووضع متابعة لمنع عودة الاختلال.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'توزيع جميع المهام بالتساوي العددي دون اعتبار للخبرة أو التعقيد.', 3, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'انتظار أن يطلب الأعضاء المتضررون المساعدة بأنفسهم.', 2, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-14', 4, 'اختلاف بين خبير ومدير مشروع', 'أوصى خبير فني بمسار محدد، بينما يرى مدير المشروع أن هذا المسار سيؤخر التنفيذ ويزيد التكلفة. كلا الطرفين يمتلك أدلة جزئية، وبدأ الخلاف يتحول إلى صراع مكانة.', 'ESCALATION', 'FULL', 'الخيار (C) يعيد الخلاف إلى معايير وأدلة، ويستفيد من الخبرة والمسؤولية معاً، ويقلل عدم اليقين بالتجربة.', 'حسم الخلاف على أساس المنصب أو التخصص وحده.', 'عندما تتعارض السلطة والخبرة، اجعل معايير القرار والأدلة هي المرجع.', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'اعتماد رأي مدير المشروع لأنه صاحب المسؤولية الإدارية النهائية.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'اعتماد رأي الخبير لأن المسألة فنية بالدرجة الأولى.', 2, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'تحديد معايير القرار والمخاطر، ومقارنة الأدلة، واختبار الخيار الحرج على نطاق محدود إن أمكن، وتوضيح حدود القرار والمسؤولية، ثم توثيق النتيجة.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'رفع الخلاف مباشرة إلى أعلى مسؤول ليختار أحد الرأيين.', 3, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-15', 1, 'اكتشاف خطأ شخصي قبل اجتماع تنفيذي', 'قبل اجتماع تنفيذي بوقت قصير اكتشفت أن تحليلاً أعددته يحتوي خطأً قد يؤثر في التوصية. يمكن تصحيح الجزء الرئيس، لكن لن يتوفر وقت لإعادة إعداد جميع المواد.', 'ESCALATION', 'FULL', 'الخيار (B) يحمي جودة القرار، ويميز بين المعلوم وغير المؤكد، ويقدم معالجة عملية من دون إخفاء أو تهويل.', 'إخفاء الخطأ لحماية الصورة الشخصية، أو إيقاف العمل كله رغم إمكانية التصحيح الجزئي.', 'تحت الضغط، الثقة تحُمى بالشفافية والحل، لا بإخفاء الخطأ.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'تصحيح المواد بعد الاجتماع ما دام احتمال اكتشاف الخطأ منخفضاً.', 2, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'إبلاغ الجهة المعنية فوراً، وتحديد أثر الخطأ، وتقديم الأرقام المصححة وما بقي غير مؤكد، واقتراح إجراء لتحديث المواد وتحمل المسؤولية.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'إرجاع الخطأ إلى مصدر البيانات لأنه زودك بمعلومات غير دقيقة.', 1, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'طلب إلغاء الاجتماع من دون توضيح السبب حتى تكتمل المراجعة.', 3, 0, 4);

