SET NAMES utf8mb4;

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-21', 4, 'HARD', 'FULL', 'متغيران اتجاهيان مستقلان', 'دوران مستقل لعنصرين', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'نلاحظ وجود عنصرين في كل إطار: سهم وخط مستقيم يتقاطعان في المركز.', 'كل عنصر يدور بشكل مستقل: 1) السهم يدور بمقدار 90 درجة باتجاه عقارب الساعة في كل خطوة (أعلى، يمين، أسفل، يسار). 2) الخط المستقيم يدور بمقدار 45 درجة باتجاه عقارب الساعة في كل خطوة (أفقي، مائل لليسار، عمودي، مائل لليمين).', 'في الإطار الرابع، السهم يشير لليسار والخط مائل لليمين (/). بتطبيق القاعدة، يجب أن يدور السهم 90 درجة ليصبح مشيراً للأعلى، ويدور الخط 45 درجة ليصبح أفقياً. هذا يعيدنا لنفس شكل الإطار الأول، وهو ما يطابق الخيار D.', 'D', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'سهم يشير للأعلى فقط', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'سهم يشير لليمين فقط', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'سهم يشير للأعلى يقطعه خط مائل', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'سهم يشير للأعلى يقطعه خط أفقي', 1, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'سهم يشير لليسار فقط', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-22', 4, 'HARD', 'FULL', 'الشكل والتظليل والموقع', 'تغير دوري في 3 خصائص', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'يوجد شكل هندسي واحد في كل إطار يتغير في نوعه، لونه، وموقعه.', 'هناك 3 قواعد متزامنة: 1) الشكل: يتسلسل (مثلث، مربع، دائرة) ويعاد. 2) التظليل: يتناوب (أسود، أبيض). 3) الموقع: باستثناء الإطار الأول الشاذ في المنتصف، تتحرك الأشكال في زوايا المربع باتجاه عقارب الساعة (أعلى اليمين -> أسفل اليمين -> أسفل اليسار -> أعلى اليسار).', 'تطبيق القواعد على الإطار الخامس: 1) الشكل التالي بعد المثلث هو المربع. 2) اللون التالي بعد الأبيض هو الأسود. 3) الموقع التالي بعد أسفل اليسار هو أعلى اليسار في التسلسل الزاوي. النتيجة هي مربع أسود في أعلى اليسار، مما يطابق الخيار B.', 'B', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'مربع أسود في أعلى اليمين', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'مربع أسود في أعلى اليسار', 1, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'دائرة سوداء في أعلى اليسار', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'مربع أبيض في أسفل اليسار', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'مثلث أسود في أعلى اليسار', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-23', 4, 'MEDIUM', 'FULL', 'إزالة المشترك والاحتفاظ بالمختلف', 'دمج وحذف (عملية XOR)', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'مصفوفة من الأشكال (3 صفوف × 3 أعمدة). كل خلية تحتوي على شكلين صغيرين.', 'يتم دمج محتويات العمودين الأول والثاني لإنتاج العمود الثالث في كل صف بناءً على قاعدة الإلغاء (الحصري): الأشكال التي تظهر في كلا العمودين يتم حذفها، والأشكال غير المكررة (المختلفة) يتم الاحتفاظ بها ونقلها للعمود الثالث.', 'في الصف الثالث: العمود الأول يحتوي على (دائرة، معين)، والعمود الثاني يحتوي على (معين، مربع). الشكل المشترك هو (المعين)، لذا يتم حذفه. الأشكال المتبقية هي (دائرة) من الأول و(مربع) من الثاني. إذن، الخلية الثالثة يجب أن تحتوي على (دائرة ومربع)، وهذا يطابق الخيار A.', 'A', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'دائرة ومربع', 1, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'معين ومربع', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'دائرة فقط', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'دائرة ومعين', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'مربع ومعين', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-24', 4, 'MEDIUM', 'FULL', 'استخراج العنصر المشترك', 'تقاطع الأشكال (عملية AND)', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'مصفوفة (3×3) تعمل أفقياً. العمودان الأول والثاني يحتويان على أزواج من الأشكال الصغيرة، والعمود الثالث يحتوي على شكل واحد كبير.', 'الشكل في العمود الثالث هو العنصر المشترك الوحيد الموجود في كل من العمودين الأول والثاني لنفس الصف، ويتم تكبيره ووضعه في المنتصف، مع تجاهل باقي الأشكال.', 'في الصف الثالث، العمود الأول يحتوي على (مثلث ومربع). العمود الثاني يحتوي على (مربع ومعين). الشكل المشترك الوحيد بينهما هو المربع. لذا يجب أن يكون الشكل في العمود الثالث مربعاً كبيراً. هذا يطابق الخيار E.', 'E', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'مثلث كبير يشير لليسار', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'معين كبير', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'دائرة كبيرة', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'شكل زائد (صليب) كبير', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'مربع كبير', 1, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-25', 4, 'HARD', 'FULL', 'الموقع والتظليل يتغيران وفق دورتين', 'دوران شكلين وتناوب التظليل', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'يوجد إطار يحتوي على عنصرين (مثلث ودائرة) في زاويتين متقابلتين قطرياً.', 'هناك مساران مستقلان: 1) يتحرك كلا الشكلين خطوة واحدة باتجاه عقارب الساعة من زاوية إلى أخرى في كل إطار، مع بقائهما متقابلين قطرياً. 2) يتناوب تظليل كل شكل بين الأسود والأبيض في كل خطوة. (المثلث دائماً يحتفظ باتجاهه مشيراً لليسار).', 'في الإطار الرابع، المثلث أبيض في أسفل اليسار، والدائرة سوداء في أعلى اليمين. بالتحرك خطوة باتجاه عقارب الساعة، سينتقل المثلث إلى أعلى اليسار، وتنتقل الدائرة إلى أسفل اليمين. بتطبيق تناوب التظليل، يصبح المثلث أسود وتصبح الدائرة بيضاء. هذا الشكل مطابق تماماً للإطار الأول، ويمثله الخيار C.', 'C', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'مثلث أبيض في أعلى اليسار ودائرة سوداء في أسفل اليمين', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'مثلث أسود في أعلى اليمين ودائرة بيضاء في أسفل اليسار', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'مثلث أسود في أعلى اليسار ودائرة بيضاء في أسفل اليمين', 1, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'مثلث أسود في أسفل اليسار ودائرة بيضاء في أعلى اليمين', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'دائرة سوداء في أعلى اليسار ومثلث أبيض في أسفل اليمين', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-26', 4, 'EASY', 'FULL', 'تحويل عدد العناصر إلى سلسلة', 'متتالية عددية متزايدة', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'سلسلة من الإطارات تحتوي على نقاط تتزايد أعدادها بصورة منتظمة ويتم ترتيبها في صفوف تتسع لـ 4 نقاط كحد أقصى.', 'عدد النقاط يتبع متتالية حسابية حيث يزيد معدل الإضافة بمقدار 1 في كل خطوة. الفروقات هي (+1، +2، +3، +4). التسلسل العددي لعدد النقاط هو: 1، 2، 4، 7، 11.', 'الإطار الخامس يحتوي على 11 نقطة. باتباع النمط، الزيادة القادمة يجب أن تكون +5. إذن عدد النقاط المطلوب في الإطار السادس هو 11 + 5 = 16 نقطة. الشكل الذي يحتوي على 16 نقطة مرتبة بانتظام في شبكة (4×4) كاملة هو الخيار D.', 'D', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', '12 نقطة (3 صفوف × 4 أعمدة)', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', '14 نقطة', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', '15 نقطة', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', '16 نقطة (شبكة كاملة 4×4)', 1, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', '10 نقاط', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-27', 4, 'MEDIUM', 'FULL', 'دورة الشكل ودورة موضع النقطة', 'دورتان مستقلتان (طول 3 وطول 4)', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'كل إطار يحتوي على شكل هندسي وبداخله نقطة صغيرة ملاصقة للحافة الداخلية.', 'يوجد مساران للتغير بمدد دورية مختلفة: 1) مسار الشكل: يتناوب في دورة ثلاثية (مربع، دائرة، مثلث) وتتكرر. 2) مسار النقطة: يتناوب موقع النقطة في دورة رباعية (يسار، يمين، أعلى، أسفل) وتتكرر.', 'بالنظر للإطار الخامس (دائرة بداخلها نقطة على اليسار): 1) الشكل التالي في الدورة الثلاثية بعد الدائرة هو (مثلث). 2) الموقع التالي في الدورة الرباعية بعد اليسار هو (يمين). بدمج الخصائص، يجب أن يكون الشكل مثلثاً بداخله نقطة على اليمين. هذا يطابق الخيار B.', 'B', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'مثلث بداخله نقطة في اليسار', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'مثلث بداخله نقطة في اليمين', 1, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'مربع بداخله نقطة في اليسار', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'دائرة بداخلها نقطة في اليسار', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'معين بداخله نقطة في اليمين', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-28', 4, 'HARD', 'FULL', 'تتبع مسارين على حدود ثابتة', 'حركة خطية بارتداد وسرعات مختلفة', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'يوجد خط أفقي عليه 5 نقاط ثابتة كمسار. تتحرك عليه نقطة سوداء من الأعلى ودائرة بيضاء من الأسفل.', 'كلا العنصرين يتحرك جيئة وذهاباً (يرتد عند الوصول للأطراف) ولكن بسرعات مختلفة: 1) النقطة السوداء تتحرك بمقدار خطوة واحدة في كل إطار. مسارها: 1، 2، 3، 4، 5، 4... 2) الدائرة البيضاء تتحرك بمقدار خطوتين في كل إطار. مسارها: 5، 3، 1، 3، 5، 3...', 'في الإطار السادس، النقطة السوداء في الموقع (4) متجهة لليسار، والدائرة البيضاء في الموقع (3) متجهة لليسار. في الإطار السابع، ستتحرك النقطة السوداء خطوة لتصبح في المنتصف (الموقع 3)، وتتحرك الدائرة البيضاء خطوتين لترتد وتصل إلى أقصى اليسار (الموقع 1). هذا التكوين يطابق الخيار A.', 'A', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'نقطة سوداء في المنتصف (الموقع 3) ودائرة بيضاء في أقصى اليسار (الموقع 1)', 1, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'نقطة سوداء في المنتصف ودائرة بيضاء في أقصى اليمين', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'نقطة سوداء في الموقع 2 ودائرة بيضاء في أقصى اليسار', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'نقطة سوداء في الموقع 4 ودائرة بيضاء في أقصى اليسار', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'النقطتان متطابقتان في المنتصف', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-29', 4, 'EASY', 'FULL', 'الغلاف والاتجاه والتظليل', 'تغير دوري لثلاثة خصائص', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'يوجد إطار خارجي مفرغ (مربع أو دائري) يحتوي على مثلث مصمت يتغير لونه واتجاهه.', 'هناك 3 قواعد دورية: 1) الإطار الخارجي يتناوب بين المربع والدائرة. 2) تظليل المثلث يتناوب بين الأسود والأبيض. 3) اتجاه المثلث يدور بمقدار 90 درجة باتجاه عقارب الساعة في كل إطار متتالٍ (يسار، أعلى، يمين، أسفل).', 'بالنسبة للإطار الخامس: الإطار التالي بعد الدائري هو (مربع). التظليل التالي بعد الأبيض هو (أسود). الاتجاه التالي للمثلث بعد الأسفل هو الدوران 90 درجة ليصبح مشيراً لـ (اليسار). الشكل الناتج هو مربع بداخله مثلث أسود يشير لليسار، وهو يطابق تماماً شكل الإطار الأول ويمثله الخيار E.', 'E', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'إطار دائري، مثلث أسود يشير لليسار', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'إطار مربع، مثلث أبيض يشير لليسار', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'إطار مربع، مثلث أسود يشير للأعلى', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'إطار دائري، مثلث أبيض يشير للأعلى', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'إطار مربع، مثلث أسود يشير لليسار', 1, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-30', 4, 'EASY', 'FULL', 'دورتان صفية وعمودية', 'إزاحة في مصفوفة (مربع لاتيني)', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'مصفوفة 3×3 تحتوي على 3 أشكال محددة بخواصها الثابتة: (دائرة بيضاء، مثلث رمادي يشير لليسار، مربع أسود).', 'تتبع المصفوفة نمط الإزاحة الدورانية. التسلسل الأساسي للأشكال في الصف الأول (دائرة، مثلث، مربع) يُزاح بمقدار خطوة واحدة لليسار في كل صف يليه. الأشكال تحتفظ دائماً بخصائصها الفردية (لونها واتجاهها) أينما وُجدت في المصفوفة.', 'بالنظر للصف الثالث، يبدأ التسلسل بالمربع الأسود، يليه الدائرة البيضاء. لإكمال الدورة الثلاثية، الشكل المتبقي والمطلوب في الخلية الفارغة هو المثلث الرمادي الذي يشير لليسار. هذا يطابق الخيار C.', 'C', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'مثلث أبيض يشير لليسار', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'مربع رمادي', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'مثلث رمادي يشير لليسار', 1, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'دائرة سوداء', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'معين رمادي', 0, 5);

