SET NAMES utf8mb4;

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-11', 4, 'MEDIUM', 'FULL', 'قاعدة اتجاه وقاعدة تظليل', 'تغير في الاتجاه والتظليل', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'نلاحظ سلسلة من المثلثات تتغير في اتجاهها ولونها (التظليل) عبر الإطارات المتعاقبة.', 'توجد قاعدتان تعملان معاً: 1) قاعدة الاتجاه: يدور المثلث بمقدار 90 درجة باتجاه عقارب الساعة في كل خطوة (يسار -> أعلى -> يمين -> أسفل). 2) قاعدة التظليل: يتناوب لون المثلث بين الأسود والأبيض.', 'الإطار الرابع هو مثلث أبيض يشير للأسفل. بتطبيق الدوران 90 درجة باتجاه عقارب الساعة، يجب أن يشير المثلث القادم لليسار. وبتطبيق قاعدة التناوب اللوني، يجب أن يتغير من الأبيض إلى الأسود. لذا، الشكل المطلوب هو مثلث أسود يشير لليسار، وهو ما يطابق الخيار C.', 'C', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'مثلث أبيض يشير لليسار', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'مثلث أسود يشير للأعلى', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'مثلث أسود يشير لليسار', 1, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'مثلث أبيض يشير لليمين', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'مثلث أسود يشير للأسفل', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-12', 4, 'EASY', 'FULL', 'تتبع عنصرين مستقلين', 'حركة مستقلة لعنصرين', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'يحتوي كل إطار على عنصرين: دائرة سوداء ومربع أبيض، يتحركان عبر الزوايا الأربع للإطار.', 'كل عنصر يتحرك بشكل مستقل من زاوية إلى الزاوية المجاورة لها باتجاه عقارب الساعة في كل خطوة. وهما دائماً متقابلان قطرياً.', 'في الإطار الرابع، الدائرة السوداء في أسفل اليسار والمربع الأبيض في أعلى اليمين. بحركتهما خطوة واحدة باتجاه عقارب الساعة، ستنتقل الدائرة إلى أعلى اليسار، وينتقل المربع إلى أسفل اليمين، ليعودا إلى نفس موضع الإطار الأول. هذا يطابق الخيار A.', 'A', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'دائرة سوداء أعلى اليسار، مربع أبيض أسفل اليمين', 1, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'دائرة سوداء أعلى اليمين، مربع أبيض أسفل اليسار', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'دائرة سوداء أعلى اليسار، مربع أبيض أسفل اليسار', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'مربع أبيض أعلى اليمين، دائرة سوداء أسفل اليمين', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'دائرة سوداء في المنتصف، مربع أبيض أسفل اليمين', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-13', 4, 'EASY', 'FULL', 'كمية وشكل يعملان معاً', 'تغير في العدد والشكل', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'السلسلة تعرض أشكالاً هندسية تتزايد في العدد وتتغير في النوع من إطار لآخر.', '1) الكمية: يزداد عدد الأشكال بمقدار واحد في كل إطار متعاقب (1، 2، 3، 4...). 2) الشكل: تتناوب الأشكال في دورة (دائرة، مثلث يشير لليسار، مربع).', 'الإطار الرابع يحتوي على 4 دوائر. بالتالي، الإطار الخامس يجب أن يحتوي على 5 أشكال. بناءً على دورة الأشكال (التي تعود إلى المثلث بعد الدائرة)، يجب أن تكون هذه الأشكال الخمسة مثلثات تشير لليسار. هذا يطابق الخيار E.', 'E', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'أربع نقاط سوداء في الأعلى ونقطة في الأسفل', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'أربع نقاط سوداء في منتصف الشكل', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'خمسة مربعات سوداء متلاصقة أفقياً', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'مثلثان أسودان يشيران لليسار', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'خمسة مثلثات سوداء تشير لليسار', 1, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-14', 4, 'MEDIUM', 'FULL', 'قاعدتان دوريتان', 'دوران وحركة نقطة', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'نلاحظ إطاراً مقسوماً بخط قطري، وتوجد نقطة سوداء تتحرك في الزوايا.', 'تعمل قاعدتان بشكل دوري: 1) الخط القطري يتبادل اتجاهه ذهاباً وإياباً بين المائل لليمين (/) والمائل لليسار (\). 2) النقطة السوداء تتحرك من زاوية إلى الزاوية المجاورة باتجاه عقارب الساعة في كل خطوة.', 'في الإطار الرابع، الخط مائل لليسار (\) والنقطة في أسفل اليسار. في الإطار الخامس، يجب أن ينعكس الخط ليصبح (/)، وتتحرك النقطة خطوة للأعلى باتجاه عقارب الساعة لتصبح في أعلى اليسار. النقطة دائماً منفصلة ولا تندمج مع الخط في النمط الأساسي. هذا يطابق الخيار B.', 'B', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'خط (\) ونقطة على الخط في أعلى اليسار', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'خط (/) ونقطة مستقلة في أعلى اليسار', 1, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'خط (/) ونقطة على الخط في أعلى اليمين', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'خط (\) ونقطة على الخط في أسفل اليمين', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'خط (/) ونقطة على الخط في أسفل اليسار', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-15', 4, 'MEDIUM', 'FULL', 'دمج محتوى الخليتين', 'دمج أشكال', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'يتم عرض الأشكال في شبكة مصفوفة (3 صفوف × 3 أعمدة).', 'تقرأ القاعدة أفقياً في كل صف. الشكل في العمود الثالث ينتج عن دمج (أو تراكب) الشكلين الموجودين في العمودين الأول والثاني من نفس الصف.', 'في الصف الثالث، الخلية الأولى تحتوي على معين، والخلية الثانية تحتوي على شكل زائد (صليب). بدمجهما معاً بوضع أحدهما داخل أو فوق الآخر، نحصل على معين بداخله شكل زائد. هذا يطابق الخيار D.', 'D', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'شكل زائد (صليب) فقط', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'معين فقط', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'معين وبجواره دائرة صغيرة', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'معين وبداخله شكل زائد (صليب)', 1, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'مربع وبداخله شكل زائد (صليب)', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-16', 4, 'MEDIUM', 'FULL', 'طرح العنصر المشترك', 'طرح أشكال', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'مصفوفة أشكال (3 صفوف × 3 أعمدة) حيث تتفاعل الأشكال أفقياً في كل صف.', 'الشكل في العمود الثالث هو ناتج عملية (طرح أشكال) أفقية. يتم حذف الشكل الموجود في العمود الثاني من مجموعة الأشكال الموجودة في العمود الأول، وما يتبقى يوضع في العمود الثالث.', 'في الصف الثالث، العمود الأول يحتوي على (معين + شكل زائد). العمود الثاني يحتوي على (معين). عند حذف (المعين) من أشكال العمود الأول، يتبقى لدينا (شكل زائد) فقط. هذا يطابق الخيار C.', 'C', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'معين', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'دائرة', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'شكل زائد (صليب)', 1, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'مربع', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'معين وشكل زائد', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-17', 4, 'HARD', 'FULL', 'اتجاه السهم يحدد حركة النقطة في اللوحة التالية', 'تأثير عنصر على آخر', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'كل إطار يحتوي على نقطة سوداء وسهم مستقلان ظاهرياً.', '1) يدور السهم 90 درجة باتجاه عقارب الساعة في كل خطوة متعاقبة. 2) اتجاه حركة النقطة من إطار إلى الإطار الذي يليه يحدده اتجاه السهم في الإطار السابق (مثال: سهم الإطار الثالث يشير لليسار، لذا النقطة في الإطار الرابع تحركت لليسار مقارنة بموقعها في الإطار الثالث).', 'السهم في الإطار الرابع يشير للأعلى، لذا النقطة في الإطار الخامس يجب أن تتحرك للأعلى من موقعها السابق (أسفل اليسار)، لتستقر في أعلى اليسار. وباتباع دورة السهم، يجب أن يدور بمقدار 90 درجة من الأعلى ليصبح مشيراً لليمين. الخيار الذي يحقق الشرطين هو A.', 'A', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'نقطة في أعلى اليسار وسهم يشير لليمين', 1, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'نقطة في أعلى اليسار وسهم يشير للأعلى', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'نقطة في أسفل اليمين وسهم يشير لليمين', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'نقطة في أعلى اليسار وسهم يشير للأسفل', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'نقطة في أسفل اليسار وسهم يشير لليسار', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-18', 4, 'MEDIUM', 'FULL', 'تغيران مستقلان', 'تغير في الشكل الخارجي وحركة النقطة', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'سلسلة من الأشكال الهندسية الخارجية وبداخل كل منها نقطة سوداء محاذية للمحيط.', 'يوجد مساران مستقلان للتغير: 1) الشكل الخارجي يتناوب في تسلسل (دائرة، مربع، مثلث، ويعود للدائرة). 2) النقطة الداخلية تتحرك بشكل دائري وهمي بمقدار 90 درجة باتجاه عقارب الساعة في كل خطوة (أعلى، يمين، أسفل، يسار).', 'بما أن الإطار الرابع هو دائرة، يجب أن يكون الإطار الخامس هو الشكل التالي في التسلسل وهو (مربع). والنقطة في الإطار الرابع كانت في (اليسار)، لذا بحركتها 90 درجة ستعود إلى موضع (الأعلى). الشكل المطلوب هو مربع بداخله نقطة في الأعلى، وهو ما يطابق الخيار E.', 'E', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'مربع بداخله نقطة في اليمين', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'مثلث بداخله نقطة في الأعلى', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'دائرة بداخلها نقطة في الأعلى', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'مربع بداخله نقطة في اليسار', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'مربع بداخله نقطة في الأعلى', 1, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-19', 4, 'HARD', 'FULL', 'قواعد مختلفة للمواقع الفردية والزوجية', 'نمطان متداخلان', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'سلسلة متداخلة من الأشكال، حيث تشير القاعدة صراحة لوجود نمطين منفصلين.', 'المواقع الفردية (1، 3، 5) تتبع سلسلة من الأشكال البيضاء المتغيرة (دائرة، مربع، مثلث). المواقع الزوجية (2، 4، ...) تمتلك شكل المعين كشكل ثابت، وتتناوب في التظليل بين الأبيض والغامق.', 'الإطار المطلوب هو رقم 6 (موقع زوجي). بالنظر للمواقع الزوجية السابقة، الإطار الثاني كان معيناً أبيض، والإطار الرابع كان معيناً غامقاً/أسود. باستكمال نمط التناوب، الإطار السادس يجب أن يعود ليصبح معيناً أبيض. هذا يطابق الخيار A.', 'A', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'معين أبيض', 1, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'معين أسود', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'مثلث أسود', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'مربع أسود', 0, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'دائرة سوداء', 0, 5);

INSERT INTO gcat_questions (item_code, subtest_id, difficulty, exam_mode, title_ar, pattern_type_ar, prompt_text_ar, observation_ar, rule_ar, application_ar, correct_option_key, is_active, exposure_count, created_at) VALUES ('GCAT-ABS-20', 4, 'EASY', 'FULL', 'زيادة اثنين ثم نقصان واحد', 'تغير كمي متناوب', 'اختر الشكل الذي يكمل النمط وفق القاعدة الأكثر اتساقاً.', 'مستطيل مقسم إلى خمسة أشرطة أفقية، يتم تظليل عدد متغير منها باللون الأسود.', 'التغير في عدد الأشرطة المظللة يتبع نمطاً حسابياً متناوباً كما هو موضح في العنوان: يضاف شريطان للتظليل، ثم يطرح شريط واحد في الخطوة التالية (+2، -1، +2، -1).', 'تسلسل عدد الأشرطة هو: 1 -> (1+2)=3 -> (3-1)=2 -> (2+2)=4 -> (4-1)=3. الإطار الأخير (الخامس) فيه 3 أشرطة سوداء، الخطوة التالية في القاعدة هي الزيادة بمقدار اثنين (+2). لذا 3 + 2 = 5 أشرطة مظللة، مما يعني تظليل المستطيل بالكامل. هذا يطابق الخيار D.', 'D', 1, 0, NOW());
SET @question_id = LAST_INSERT_ID();
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'A', 'مستطيل به 3 أشرطة سوداء من الأعلى', 0, 1);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'B', 'مستطيل به شريط أسود واحد', 0, 2);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'C', 'مستطيل به 4 أشرطة سوداء', 0, 3);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'D', 'مستطيل أسود بالكامل', 1, 4);
INSERT INTO gcat_options (question_id, option_key, option_text_ar, is_correct, display_order) VALUES (@question_id, 'E', 'مستطيل به شريطان أسودان', 0, 5);

