SET NAMES utf8mb4;

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-16', 1, 'توزيع موارد محدودة على عدة مشاريع', 'لديك موارد محدودة وثلاثة مشاريع تتنافس عليها. لكل مشروع قيمة وأثر ومخاطر مختلفة.', 'TRADE_OFF', 'FULL', 'الخيار (B) هو الأكثر منهجية وشفافية، بينما الخيار (D) قوي لكنه أقل تحديداً في معايير القرار.', 'اعتبار التوزيع المتساوي عادلاً رغم اختلاف الأولويات.', 'العدالة في تخصيص الموارد تعني وضوح المعايير، لا المساواة الآلية.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'توزيع الموارد بالتساوي بين المشاريع حتى لا تشعر أي جهة بعدم الإنصاف.', 2, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'استخدام مصفوفة شفافة للأثر والاستعجال والمخاطر والاعتماديات، ثم تخصيص الموارد ووضع نقاط مراجعة.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'منح الموارد للمشروع الأكثر ظهوراً أمام الإدارة العليا.', 1, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'استشارة قادة المشاريع، وتخصيص الموارد حسب الأولويات، والإبقاء على احتياطي صغير للمستجدات.', 4, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-17', 5, 'شائعة عن إعادة هيكلة محتملة', 'انتشرت شائعة عن إعادة هيكلة، ولا توجد معلومات رسمية يمكنك إعلانها. بدأ القلق يؤثر في التركيز.', 'DIRECT', 'FULL', 'الخيار (C) يقدم صدقاً دون كشف غير مصرح أو تكهن، و (D) يعالج الحاجة التنظيمية للتواصل.', 'اعتبار مشاركة الشائعة شفافية، أو إسكات القلق بالسلطة.', 'الشفافية لا تعني قول ما لا تعرفه؛ بل توضيح حدود المعرفة وما سيحدث تالياً.', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'مشاركة ما سمعته بصورة غير رسمية حتى يشعر الفريق أنك صريح معهم.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'منع الحديث عن الموضوع والتحذير من تكرار الشائعات.', 2, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'توضيح أنه لا توجد معلومات مؤكدة يمكن مشاركتها، وتجنب التكهن، وتوجيه الفريق إلى القنوات الرسمية ومواصلة تحديثهم عند توفر معلومة.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'إبلاغ الموارد البشرية أو الإدارة بأثر الغموض وطلب تواصل رسمي في أقرب وقت.', 4, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-18', 2, 'تكرار أخطاء التسليم بين فرق متعددة', 'يتأخر مشروع مشترك بسبب أخطاء متكررة عند انتقال العمل من فريق إلى آخر. كل فريق يرى أن المشكلة في الطرف الآخر.', 'TRADE_OFF', 'FULL', 'الخيار (B) يعالج البنية الجذرية للتسليم، و (D) يوفر آلية متابعة مناسبة بعد توضيح البنية.', 'محاولة حل خلل العملية برسائل عامة عن التعاون.', 'عند تعثر التنسيق، افحص الواجهة والمعيار والملكية قبل لوم الفرق.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'إرسال رسالة تذكير للجميع بأهمية التعاون والالتزام بالمواعيد.', 2, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'رسم سير العمل، وتحديد مالك كل تسليم ومعايير القبول ونقاط التحكم بين الفرق.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'تكليف فريق واحد بإدارة جميع عمليات التنسيق نيابة عن بقية الفرق.', 3, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'إنشاء لوحة متابعة مشتركة واجتماع تنسيق قصير لمعالجة التعثرات قبل موعد التسليم.', 4, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-19', 2, 'توتر متكرر بين عضوين', 'يتكرر التوتر بين عضوين، وبدأ يظهر في الاجتماعات ويؤثر في التعاون.', 'DIRECT', 'FULL', 'الخيار (B) يعالج الأسباب والتصورات، ويحولها إلى اتفاقات قابلة للمتابعة.', 'الهروب من الخلاف بالفصل، أو الاكتفاء برسالة عامة.', 'الحل المستدام يواجه الخلاف بأمان واحترام، لا يخفيه.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'فصل العضوين بصورة دائمة في مسارات عمل مختلفة.', 2, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'الحديث مع كل طرف منفرداً، ثم إدارة جلسة مشتركة تركز على الوقائع والأثر والاتفاقات السلوكية والمتابعة.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'تجاهل الخلاف ما دام كل منهما ينجز مهامه الأساسية.', 1, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'تذكير الفريق كله بقواعد الاحترام من دون معالجة الخلاف مباشرة.', 3, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-20', 3, 'طلبات عاجلة متزامنة', 'تلقيت في الوقت نفسه عدة طلبات عاجلة من جهات مختلفة، وكل جهة تصف طلبها بأنه أولوية. لا يمكن لفريقك إنجازها جميعاً في المواعيد المطلوبة.', 'TRADE_OFF', 'FULL', 'الخيار (B) يضع معايير واضحة ويمنع الوعود غير الواقعية، بينما (D) قد يفيد لكنه يتخلى جزئياً عن دور القائد في التقييم.', 'مساواة الاستعجال المعلن بالأولوية الحقيقية، أو قبول التزامات غير قابلة للتحقيق.', 'الضغط لا يلغي الأولويات؛ بل يجعلها أكثر ضرورة.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'البدء بالطلب الذي وصل أولاً حفاظاً على العدالة.', 2, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'تقييم الأثر والاستعجال والمخاطر، وتحديد الأولويات والتفويض، ثم إبلاغ الجهات بالمفاضلات والمواعيد الواقعية.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'قبول جميع المواعيد وتوزيع الضغط على الفريق بالتساوي.', 1, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'مطالبة الجهات الطالبة بالتفاوض فيما بينها وتحديد ما يجب إنجازه أولاً.', 3, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-21', 5, 'اقتراح مبتكر لم يُختبر', 'اقترح موظف حلاً مبتكراً قد يخفض الوقت والتكلفة، لكنه لم يُجرّب في بيئتكم ويحتاج بعض التعديل.', 'TRADE_OFF', 'FULL', 'الخيار (C) يوازن التعلم والسرعة والمخاطر، و (D) خطوة قوية تسبق التجربة لكنها أقل اكتمالاً.', 'رفض الجديد بالكامل أو تبنيه بالكامل قبل توليد أدلة.', 'التجريب المنضبط هو الجسر بين الابتكار والاعتماد.', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'رفض الاقتراح لأن المخاطر غير معروفة ولأن الإجراء الحالي يعمل.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'اعتماد الحل على نطاق كامل للاستفادة من الفرصة قبل غيركم.', 1, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'تنفيذ تجربة محدودة بمعايير نجاح وضوابط ومراجعة، ثم اتخاذ قرار التوسع بناءً على النتائج.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'طلب دراسة جدوى ومراجعة فنية أولية قبل تصميم تجربة محدودة.', 4, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-22', 2, 'سوء فهم في فريق يعمل عن بُعد', 'فهم أحد أعضاء الفريق عن بُعد رسالة بريدية بطريقة مختلفة، ونفذ جزءاً من المهمة بصورة غير صحيحة.', 'DIRECT', 'FULL', 'الخيار (B) يستخدم قناة تفاعلية ثم يوثق، و (D) يدعم الفهم عملياً لكنه لا يستكشف سبب الالتباس بالقدر نفسه.', 'زيادة طول الرسالة من دون تغيير القناة أو التحقق من الفهم.', 'عندما تفشل قناة، غيّر القناة ثم وثق الاتفاق.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'إرسال رسالة أطول تشرح جميع التفاصيل مرة أخرى.', 2, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'إجراء مكالمة قصيرة لتوضيح المطلوب، وطلب إعادة شرحه بكلماته، ثم إرسال خلاصة مكتوبة ونقطة تحقق.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'إضافة مدير الموظف في الرسالة وبيان أن التعليمات كانت واضحة.', 1, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'إرسال مثال أو نموذج مكتمل وطلب تأكيد الفهم قبل استكمال التنفيذ.', 4, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-23', 2, 'نَسب نجاح المشروع', 'نجح مشروع قاده فريقك، وطُلب منك عرضه أمام الإدارة. كان لبعض الأعضاء دور بارز، بينما أسهم آخرون بأعمال أقل ظهوراً لكنها ضرورية.', 'DIRECT', 'FULL', 'الخيار (B) يربط الاعتراف بالإنجاز المحدد وبالتعلم المشترك، ويعطي صورة عادلة عن مساهمة الفريق.', 'احتكار الفضل أو حصر التقدير في الأعمال الأكثر ظهوراً.', 'التقدير المحدد أكثر صدقاً وتأثيراً من الشكر العام، ويقوي السلوك الذي تريد تكراره.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'عرض النجاح بوصفه نتيجة لقيادتك وتوجيهك للفريق.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'ربط النجاح بالهدف المشترك، وذكر إسهامات محددة ومتنوعة، وتوضيح ما تعلمه الفريق.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'تقدير أصحاب الأداء الأكثر ظهوراً فقط لأنهم صنعوا الفارق الأكبر.', 2, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'شكر الفريق كله بصورة عامة من دون تمييز الإسهامات.', 3, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-24', 4, 'اختلاف في تفسير سياسة مشتركة', 'تختلف إدارتك مع إدارة أخرى في تفسير سياسة مؤسسية، وأدى ذلك إلى قرارات متعارضة وتأخر معاملات مشتركة.', 'TRADE_OFF', 'FULL', 'الخيار (B) يعالج التشغيل والفهم والحوكمة معاً، ويصعّد فقط الجزء الذي يتطلب سلطة تفسيرية.', 'التصعيد المبكر أو فرض تفسير أحادي قبل تحديد موضع الخلاف.', 'افصل بين ما يمكن الاتفاق عليه تشغيلياً وما يحتاج حكماً رسمياً.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'تجاوز الإدارة الأخرى وتطبيق تفسير إدارتك مباشرة.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'مراجعة نص السياسة وهدفها والوقائع مع الطرف الآخر، واعتماد إجراء مؤقت متفق عليه، ورفع نقطة التفسير غير المحسومة إلى الجهة المخولة.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'رفع الخلاف مباشرة إلى القيادة العليا من دون نقاش مشترك.', 3, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'الاستمرار وفق تفسير إدارتك مع توثيق أسباب القرار.', 2, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-25', 2, 'انخفاض المعنويات بعد إخفاق', 'لم يحقق الفريق نتيجة مهمة رغم جهد كبير، وظهر الإحباط واللوم المتبادل. هناك موعد جديد قريب يتطلب استعادة التركيز.', 'TRADE_OFF', 'FULL', 'الخيار (C) يجمع الاعتراف والتعلم والدعم والخطوات القصيرة التي تعيد الثقة.', 'إنكار المشاعر أو تحويل التعلم إلى لوم شخصي.', 'استعادة المعنويات لا تأتي من الخطاب وحده؛ بل من فهم ما حدث وخطة تعافٍ يمكن تنفيذها.', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'التقليل من حجم الإخفاق والتأكيد أن الأمر لا يستحق القلق.', 2, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'تحديد الأشخاص الذين تسببوا في الإخفاق حتى لا يتكرر الخطأ.', 1, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'الاعتراف بالنتيجة، وإجراء مراجعة بلا لوم، وتحديد إجراءات تعافٍ وأهداف قريبة قابلة للتحقيق، وتقديم الدعم أثناء التنفيذ.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'منح الفريق استراحة قصيرة ثم العودة إلى الخطة نفسها من دون مراجعة.', 3, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-26', 1, 'مخاطرة امتثال قبل موعد حاسم', 'اكتشفت قبل موعد تسليم حاسم أن إحدى الخطوات قد تتعارض مع متطلب امتثال، لكن تفسير المتطلب غير محسوم، وتأخير المشروع له تكلفة كبيرة.', 'ESCALATION', 'FULL', 'الخيار (C) يحمي المؤسسة، ويحد من نطاق التوقف، ويطلب تفسيراً مخولاً، ويبحث عن بديل.', 'اختيار السرعة على الامتثال، أو إيقاف كل شيء من دون تحليل نطاق المخاطرة.', 'عند مخاطر الامتثال، لا تنقل المسؤولية إلى فرد؛ عالج القرار والنظام والتوثيق.', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'الاستمرار في التنفيذ ومعالجة مسألة الامتثال بعد التسليم.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'إيقاف المشروع كله وإبلاغ الإدارة بالمخاطرة من دون اقتراح بدائل.', 3, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'إيقاف الخطوة محل المخاطرة فقط، واستشارة الجهة المختصة، وتصميم مسار بديل آمن، وتوثيق القرار والتأثير الزمني.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'تكليف الموظف المسؤول بتوقيع إقرار بتحمل مسؤولية الاستمرار.', 1, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-27', 1, 'طلب تبسيط تقرير تنفيذي بصورة مفرطة', 'طُلب منك مسؤول تنفيذي اختصار تقرير معقد إلى صفحة واحدة، لكن حذف بعض التحفظات قد يجعل الرسالة مضللة لقرار مهم.', 'ESCALATION', 'FULL', 'الخيار (C) يحقق الوضوح والاختصار من دون إخفاء المعلومات الجوهرية، ويربط المحتوى بقرار المستخدم.', 'الاختيار بين الاختصار والدقة كأنهما متعارضان دائماً.', 'التواصل التنفيذي الجيد يختصر التعقيد، لا يحذف الحقيقة.', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'حذف التحفظات وتنفيذ طلب المسؤول حرفياً لأن القرار النهائي مسؤوليته.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'رفض الاختصار وإرسال التقرير الكامل كما هو.', 2, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'إعداد ملخص تنفيذي واضح يبرز الاستنتاج والتحفظات الحرجة، وإرفاق التفاصيل، والتأكد من نوع القرار الذي سيبُنى عليه التقرير.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'إرسال صفحة مبسطة، ثم ذكر التحفظات شفهياً فقط أثناء الاجتماع.', 3, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-28', 2, 'عضو لا يسهم بسبب فجوة مهارية', 'يتأخر أحد أعضاء الفريق في تسليم مهامه، وتشير الملاحظة الأولية إلى وجود فجوة مهارية لا ضعف التزام.', 'DIRECT', 'FULL', 'الخيار (B) يوازن حماية النتيجة مع تطوير القدرة، ويجعل التحسن قابلاً للمتابعة.', 'تفسير ضعف المهارة على أنه ضعف التزام، أو نقل المشكلة إلى الفريق بلا خطة تطوير.', 'ميّز بين فجوة الإرادة وفجوة المهارة؛ فلكل منهما معالجة مختلفة.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'استبداله فوراً بعضو أكثر خبرة لحماية موعد المشروع.', 2, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'مناقشته على انفراد، وتحديد الفجوة، ووضع دعم عملي قصير، وتعديل نطاق المهمة مؤقتاً، ومتابعة التقدم بمؤشرات واضحة.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'إعادة توزيع مهامه بصورة دائمة من دون مناقشته حتى لا يشعر بالإحراج.', 2, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'مطالبة الزملاء بتغطية النقص إلى أن يتعلم بالممارسة غير الرسمية.', 3, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-29', 2, 'تحول نقاش مهني إلى نقد شخصي', 'خلال اجتماع، تحول خلاف حول فكرة إلى انتقاد شخصي بين اثنين من المشاركين، وبدأ الحضور يفقدون التركيز.', 'TRADE_OFF', 'FULL', 'الخيار (B) يوقف السلوك، ويحافظ على الموضوع، ويعيد قواعد النقاش، ويؤجل المعالجة الفردية لما بعد الاحتواء.', 'مقابلة الحدة بحدة، أو تجاهلها باسم التركيز على المهمة.', 'أوقف السلوك الشخصي فوراً، لكن لا تجعل احتواءه يلغي الهدف المهني للاجتماع.', 'B', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'الرد بحزم على الشخص الأكثر حدة وإظهار أن أسلوبه غير مقبول.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'إيقاف التبادل الشخصي، وإعادة صياغة موضوع الخلاف بصورة محايدة، وتثبيت قواعد الاحترام، ومواصلة النقاش إن أمكن مع متابعة خاصة لاحقاً.', 5, 1, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'تجاهل التعليقات والتركيز على جدول الأعمال حتى لا يتضخم الخلاف.', 2, 0, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'إنهاء الاجتماع فوراً وإحالة الطرفين إلى الموارد البشرية.', 3, 0, 4);

INSERT INTO sjt_scenarios (item_code, domain_id, title_ar, narrative_ar, complexity, exam_mode, rationale_ar, common_mistake_ar, coaching_note_ar, best_option_key, is_active, exposure_count, created_at) VALUES ('SJT-30', 3, 'تغييرات متأخرة قبل عرض حاسم', 'قبل عرض مهم بساعات، وصلت تعديلات كثيرة من عدة جهات. بعضها ضروري، وبعضها تجميلي، ولا يكفي الوقت لتطبيقها جميعاً ومراجعتها.', 'ESCALATION', 'FULL', 'الخيار (C) يطبق مفاضلة واضحة ويحمي الجودة الحرجة ويضيف تحققاً وبديلاً.', 'الموافقة أو الرفض الشامل بدلاً من الفرز حسب الأثر.', 'تحت ضغط التغيير، جمّد ما لا يضيف قيمة واحمِ نقاط الفشل الحرجة.', 'C', 1, 0, NOW());
SET @scenario_id = LAST_INSERT_ID();
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'A', 'قبول جميع التعديلات وتوزيعها على الفريق حتى لو لم يتوفر وقت للمراجعة.', 1, 0, 1);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'B', 'رفض جميع التعديلات لأن وقت المراجعة انتهى.', 2, 0, 2);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'C', 'تصنيف التعديلات حسب أثرها وضرورتها، وتجميد غير الضروري، وتعيين مسؤول تحقق، وإجراء بروفة للأجزاء المتأثرة، وتجهيز نسخة احتياطية.', 5, 1, 3);
INSERT INTO sjt_options (scenario_id, option_key, action_text_ar, effectiveness_score, is_best_action, display_order) VALUES (@scenario_id, 'D', 'تفويض التعديلات لأعضاء الفريق والثقة بأن كل شخص سيتحقق من عمله.', 3, 0, 4);

