server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/psychometric_db?createDatabaseIfNotExist=true
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.SQL=DEBUG

jwt.secret=2foqAEMlzMlNEwux/M+hHvvCw8DQJI3A1bnJVJ8K1FA=

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omarharaz553@gmail.com
spring.mail.password=dtcmfznhiiotjles
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

cors.allowed-origins=http://127.0.0.1:5500,http://localhost:5500,http://localhost:3000,http://localhost:5173,http://localhost:8080,http://localhost:8081,http://localhost:8085

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

cloudinary.cloud-name=n8ebougz
cloudinary.api-key=811295576953758
cloudinary.api-secret=UCkrZ7QOJntAUNflVQbxnOwo4Fo
cloudinary.folder=psychometric

logging.level.org.springframework.security=DEBUG



# ==========================================
# Gemini API Configuration
# ==========================================
# Replace this with your NEW generated key!
gemini.api.key=AQ.Ab8RN6IfhJmRgsHl07KaoxZ0hMKJULn6TWq4M485UTGeygdDhg

# The standard REST endpoint for Gemini Flash (Perfect for fast JSON generation)
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# (Optional) You can store your project details for internal reference
gemini.api.project.name=projects/90570892071
gemini.api.project.number=projects/90570892071
